name: EssentialsHsb
version: 1.1
author: Hashing
main: not.domain.Home
commands:
    essentialshsb:
      description: ver sobre o plugin
    essentialshsbhelp:
      description: ver os comandos
    godmode:
      description: ativar modo de resistencia
    kick:
      description: kickar jogadores
    gm:
      description: mudar o modo de jogo
    gamemode:
      description: mudar o modo de jogo
    fly:
      description: ganhar a habilidade de voar
    tpa:
      description: dar tpa em um jogador
    tpaccept:
      description: aceitar tpa
    tpadeny:
      description: cancelar tpa